// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FilePreviewController from "./file_preview_controller"
application.register("file-preview", FilePreviewController)

import FormFieldBuilderController from "./form_field_builder_controller"
application.register("form-field-builder", FormFieldBuilderController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import OtpInputController from "./otp_input_controller"
application.register("otp-input", OtpInputController)

import OtpController from "./otp_controller"
application.register("otp", OtpController)

import AuthToggleController from "./auth_toggle_controller"
application.register("auth-toggle", AuthToggleController)

import ReviewQueueController from "./review_queue_controller"
application.register("review-queue", ReviewQueueController)

import SidebarController from "./sidebar_controller"
application.register("sidebar", SidebarController)

import FormController from "./form_controller"
application.register("form", FormController)

import FieldRowController from "./field_row_controller"
application.register("field-row", FieldRowController)
