// Hometown — mock data + tiny store
// Pretends to be a real backend. State is React-managed in App.

const STARTER_USERS = [
  { id: 'u_self', name: '林知夏', handle: 'zhixia', avatar: '林', email: 'zhixia@hometown.dev', phone: '+86 138 0013 8000', role: 'Frontend', school: '清华大学', joined: '2025-09-12', bio: '前端 / 设计系统 / 喜欢做精致的小工具。', github: 'github.com/zhixia', skills: ['React', 'TypeScript', 'Figma', 'Motion'] },
  { id: 'u_admin', name: 'Avery Chen', handle: 'avery', avatar: 'A', email: 'avery@hometown.dev', phone: '+86 139 0013 9000', role: 'Admin', school: 'Hometown Team', isAdmin: true },
];

const STARTER_HACKATHON_FORM = {
  id: 'f_hack_2026',
  title: 'Hometown Hackathon 2026 · 报名表',
  description: '5月18-19日 · 上海 · 48 小时不间断 · 限 200 人',
  status: 'live',
  responses: 47,
  createdAt: '2026-04-12',
  updatedAt: '2026-04-26',
  fields: [
    { id: 'f1', type: 'short_text', label: '姓名 / 昵称', placeholder: '你想被怎样称呼？', required: true },
    { id: 'f2', type: 'email', label: '邮箱', placeholder: 'you@example.com', required: true, help: '我们会用这个邮箱发送报名结果' },
    { id: 'f3', type: 'short_text', label: '学校 / 公司', placeholder: '清华大学 · 计算机系', required: true },
    { id: 'f4', type: 'radio', label: '主要角色', required: true, options: ['前端', '后端', '设计', '产品', '其他'] },
    { id: 'f5', type: 'checkbox', label: '熟悉的技术栈', required: false, options: ['React', 'Vue', 'Swift', 'Python', 'Go', 'Rust', 'Figma', '其他'] },
    { id: 'f6', type: 'url', label: 'GitHub / 作品集链接', placeholder: 'github.com/yourname', required: false },
    { id: 'f7', type: 'long_text', label: '项目想法简述', placeholder: '一两句话讲讲你想做什么，或者你想加入什么样的队伍。', required: true, help: '不需要完整方案，只是让我们了解你' },
  ],
};

const STARTER_FORMS = [
  STARTER_HACKATHON_FORM,
  { id: 'f_meetup', title: 'Hometown Meetup #12 · 报名', description: '4月29日 · 周三晚 · Co-working Space', status: 'live', responses: 23, createdAt: '2026-04-15', updatedAt: '2026-04-22', fields: [] },
  { id: 'f_feedback', title: '社区季度反馈调研', description: '匿名 · 帮我们做得更好', status: 'draft', responses: 0, createdAt: '2026-04-20', updatedAt: '2026-04-20', fields: [] },
  { id: 'f_workshop', title: 'Design Engineering Workshop', description: '已结束 · 共 18 位参与者', status: 'closed', responses: 18, createdAt: '2026-03-01', updatedAt: '2026-03-15', fields: [] },
];

const STARTER_APPLICATIONS = [
  { id: 'a1', name: '陈思源', handle: 'siyuan', avatar: '陈', email: 'siyuan@stanford.edu', school: '斯坦福大学 · CS', role: '后端', skills: ['Go', 'Rust', 'Postgres'], github: 'github.com/siyuan', idea: '想做一个面向独立开发者的 webhook 调试工具，支持本地隧道和回放。已经有原型，希望黑客松期间能完成 v1 的发布。', submittedAt: '4 月 26 日 14:32', status: 'pending', starred: true },
  { id: 'a2', name: 'Maya Patel', handle: 'maya', avatar: 'M', email: 'maya.p@design.io', school: 'IDEO · Designer', role: '设计', skills: ['Figma', 'Motion', 'Prototyping'], github: 'maya.design', idea: '把读书笔记自动转换成卡片化播客 — 用 LLM 生成适合通勤听的 5 分钟摘要，UX 重在「断点续听」。', submittedAt: '4 月 26 日 11:08', status: 'pending', starred: false },
  { id: 'a3', name: 'Tomás Reyes', handle: 'tomas', avatar: 'T', email: 'tomas@upgrade.cl', school: '智利大学', role: '前端', skills: ['React', 'TypeScript', 'WebGL'], github: 'github.com/tomas', idea: 'WebGL 协作白板，支持多人手写笔迹同步和图层。重点解决远程团队 sketch session 卡顿的问题。', submittedAt: '4 月 25 日 22:45', status: 'pending', starred: false },
  { id: 'a4', name: '王小川', handle: 'xiaochuan', avatar: '王', email: 'xc@bytedance.com', school: 'ByteDance · 工程师', role: '后端', skills: ['Python', 'ML', 'K8s'], github: 'github.com/xc', idea: '为社区做一个隐私优先的 RSS 推荐器，本地嵌入 + 云端协同过滤，目标是在不上传阅读历史的前提下做到主流平台 80% 的推荐质量。', submittedAt: '4 月 25 日 16:20', status: 'approved', starred: false },
  { id: 'a5', name: 'Jordan Lee', handle: 'jordan', avatar: 'J', email: 'jordan@growthly.co', school: '独立开发者', role: '产品', skills: ['Figma', 'No-code', 'Analytics'], github: 'jordanlee.co', idea: '想给小型读书会做一个「主持人工具包」 — 自动生成讨论提纲、计时、轮次提醒。让线下读书更结构化但不死板。', submittedAt: '4 月 25 日 09:11', status: 'pending', starred: false },
  { id: 'a6', name: '张语桐', handle: 'yutong', avatar: '张', email: 'yutong@cmu.edu', school: 'CMU · HCI', role: '设计', skills: ['Research', 'Figma', 'SwiftUI'], github: 'yutong.work', idea: '给独居老人的「家庭日历」iPad 端 — 不依赖文字输入，全是大图标和语音。希望能跟一位 iOS 工程师组队。', submittedAt: '4 月 24 日 19:55', status: 'pending', starred: true },
  { id: 'a7', name: 'Alex Kim', handle: 'alex', avatar: 'A', email: 'alex@kim.dev', school: 'KAIST', role: '前端', skills: ['Vue', 'Nuxt', 'GraphQL'], github: 'github.com/akim', idea: '把日历事件可视化成「时间花园」 — 把任务种成植物，专注一段时间长大，分心枯萎。要做得不像番茄钟。', submittedAt: '4 月 24 日 15:33', status: 'rejected', starred: false },
  { id: 'a8', name: '李明轩', handle: 'mingxuan', avatar: '李', email: 'mx@sjtu.edu.cn', school: '上海交通大学', role: '后端', skills: ['Java', 'Spring', 'Redis'], github: 'github.com/mx', idea: '社区运营自动化工具 — 给微信群和 Discord 一起用的一个 dashboard，整合活跃度统计、积分、自动 onboard 新人。', submittedAt: '4 月 24 日 10:02', status: 'pending', starred: false },
  { id: 'a9', name: 'Priya Shah', handle: 'priya', avatar: 'P', email: 'priya@nyu.edu', school: 'NYU · ITP', role: '其他', skills: ['Arduino', 'TouchDesigner', 'p5.js'], github: 'priya.art', idea: '做一个「房间情绪灯」 — 通过摄像头识别房间里的人数和活动强度，调节灯光颜色与节奏。希望和一位前端配合做配置面板。', submittedAt: '4 月 23 日 21:14', status: 'pending', starred: false },
  { id: 'a10', name: 'Daniel Wu', handle: 'daniel', avatar: 'D', email: 'daniel@wu.io', school: 'Y Combinator W26', role: '产品', skills: ['Strategy', 'Figma', 'SQL'], github: 'wu.io', idea: '给独立创作者的「订阅数据看板」 — Substack / Patreon / 小报童一站式看，重点是趋势预测和流失预警。', submittedAt: '4 月 23 日 14:48', status: 'approved', starred: false },
];

// ─── Project gallery (post-hackathon submissions) ───
const PROJECT_TRACKS = [
  { id: 'tools', label: 'Tools for Builders', color: '#ECFCCB' },
  { id: 'agents', label: 'AI Agents', color: '#DBEAFE' },
  { id: 'creators', label: '为创作者', color: '#FCE7F3' },
  { id: 'community', label: '社区与社交', color: '#FEF3C7' },
  { id: 'health', label: '健康与生活', color: '#E0E7FF' },
  { id: 'learn', label: '学习工具', color: '#FEE2E2' },
];

const STARTER_PROJECTS = [
  {
    id: 'p1', name: 'Wormhole', tagline: '一行命令把本地端口暴露给世界 — 但首先要可视化它',
    track: 'tools', cover: '#0C0A09', coverPattern: 'grid',
    description: '我们在两天里从零搭了一个可视化的 webhook / tunnel 调试工具：把每一次进出本地服务的请求渲染成可拖动的卡片流，可以暂停、回放、改写后再次发送。底层用 Cloudflare Workers 做隧道，前端是一个画布编辑器。',
    seeking: ['找早期内测用户', '招前端协作者'],
    tech: ['React', 'WebSockets', 'Workers', 'Rust'],
    team: [{ name: '陈思源', avatar: '陈', role: '后端' }, { name: '林知夏', avatar: '林', role: '前端' }, { name: '王小川', avatar: '王', role: 'DevOps' }],
    likes: 142, comments: 18, demo: 'wormhole.dev', github: 'github.com/wormhole/cli', video: 'demo.mp4',
    submittedAt: '5 月 19 日 16:42', winner: '最佳工具',
  },
  {
    id: 'p2', name: '小报童 Daily', tagline: '把 RSS 订阅自动剪辑成 5 分钟通勤播客',
    track: 'creators', cover: '#FCE7F3', coverPattern: 'wave',
    description: '订阅你常读的 newsletter / blog，每天清晨拿到一个像电台的语音摘要。重点解决「断点续听」 — 在你下车那一刻精确暂停，第二天接上。',
    seeking: ['找投资'],
    tech: ['Swift', 'ElevenLabs', 'OpenAI'],
    team: [{ name: 'Maya Patel', avatar: 'M', role: '设计' }, { name: 'Alex Kim', avatar: 'A', role: '前端' }],
    likes: 96, comments: 24, demo: 'xiaobaotong.daily', github: '', submittedAt: '5 月 19 日 16:55',
  },
  {
    id: 'p3', name: 'Sketchpad Live', tagline: '远程 sketch 不再卡 — WebGL 协作白板',
    track: 'tools', cover: '#0EA5E9', coverPattern: 'lines',
    description: '我们做了一个 WebGL 协作白板，重点是手写笔迹的低延迟同步和多图层管理。在 50 人同屏的压测中保持 60fps。',
    seeking: ['招前端协作者', '找早期内测用户'],
    tech: ['WebGL', 'Yjs', 'TypeScript'],
    team: [{ name: 'Tomás Reyes', avatar: 'T', role: '前端' }, { name: '李明轩', avatar: '李', role: '后端' }],
    likes: 78, comments: 9, demo: 'sketchpad.live', github: 'github.com/tomas/sketchpad', submittedAt: '5 月 19 日 17:01',
  },
  {
    id: 'p4', name: 'Quiet RSS', tagline: '本地嵌入 + 云端协同过滤，但不上传你的阅读历史',
    track: 'agents', cover: '#10B981', coverPattern: 'dots',
    description: '隐私优先的 RSS 推荐器。所有阅读历史在本地嵌入，云端只做匿名向量协同过滤。在我们的离线评测中达到主流推荐器 82% 的命中率。',
    seeking: ['找投资', '招后端'],
    tech: ['Go', 'Python', 'pgvector'],
    team: [{ name: '王小川', avatar: '王', role: '后端' }],
    likes: 64, comments: 12, demo: 'quiet.rss', github: 'github.com/quiet/rss', submittedAt: '5 月 19 日 17:08',
  },
  {
    id: 'p5', name: 'Round Table', tagline: '小型读书会的「主持人工具包」',
    track: 'community', cover: '#FEF3C7', coverPattern: 'circles',
    description: '自动生成讨论提纲、计时、轮次提醒、参与度统计。让线下读书会更结构化，但保留灵活的边界。我们在三场真实读书会上做了 user testing。',
    seeking: ['找早期内测用户'],
    tech: ['Next.js', 'Tailwind', 'OpenAI'],
    team: [{ name: 'Jordan Lee', avatar: 'J', role: '产品' }, { name: '张语桐', avatar: '张', role: '设计' }],
    likes: 53, comments: 7, demo: 'roundtable.club', github: '', submittedAt: '5 月 19 日 17:14',
  },
  {
    id: 'p6', name: 'Garden Hours', tagline: '不像番茄钟的专注工具 — 把任务种成植物',
    track: 'health', cover: '#A3E635', coverPattern: 'leaves',
    description: '把日历事件可视化成一座时间花园。专注时间长，植物长大；分心，植物枯萎。我们花了大量时间在动画细节和「不打扰但有存在感」的反馈机制上。',
    seeking: ['招设计师'],
    tech: ['Vue', 'Nuxt', 'GSAP'],
    team: [{ name: 'Alex Kim', avatar: 'A', role: '前端' }],
    likes: 49, comments: 14, demo: 'garden.hours', github: 'github.com/alex/garden', submittedAt: '5 月 19 日 17:20',
  },
  {
    id: 'p7', name: 'Family Calendar', tagline: '给独居老人的 iPad 日历 — 全是大图标和语音',
    track: 'health', cover: '#F87171', coverPattern: 'rings',
    description: '不依赖文字输入。子女在云端编辑，老人端只看大图标和听语音提醒。我们和两位 75+ 老人做了原型测试，迭代了三轮交互。',
    seeking: ['找投资', '找用户'],
    tech: ['SwiftUI', 'CloudKit'],
    team: [{ name: '张语桐', avatar: '张', role: '设计' }, { name: 'Priya Shah', avatar: 'P', role: '硬件' }],
    likes: 38, comments: 6, demo: 'familycal.app', github: '', submittedAt: '5 月 19 日 17:28',
  },
  {
    id: 'p8', name: 'CommunityOS', tagline: '微信群 + Discord 双端社区运营 dashboard',
    track: 'community', cover: '#A78BFA', coverPattern: 'hex',
    description: '整合活跃度统计、积分体系、自动 onboard 新人。一个 dashboard 同时管理微信群和 Discord，避免在两个工具之间来回切。',
    seeking: ['招前端', '找早期内测用户'],
    tech: ['Java', 'Spring', 'Redis', 'React'],
    team: [{ name: '李明轩', avatar: '李', role: '后端' }],
    likes: 31, comments: 4, demo: '', github: 'github.com/mx/communityos', submittedAt: '5 月 19 日 17:33',
  },
  {
    id: 'p9', name: 'Mood Lamp', tagline: '通过摄像头识别房间情绪，调节灯光',
    track: 'health', cover: '#F472B6', coverPattern: 'waves',
    description: '硬件 + 软件作品。摄像头识别房间里的人数和活动强度，灯光颜色与节奏自动调节。希望让科技的存在感更柔和。',
    seeking: ['招前端协作者'],
    tech: ['Arduino', 'TouchDesigner', 'p5.js'],
    team: [{ name: 'Priya Shah', avatar: 'P', role: '硬件' }],
    likes: 27, comments: 3, demo: '', github: '', submittedAt: '5 月 19 日 17:40',
  },
  {
    id: 'p10', name: 'Subs Dashboard', tagline: '独立创作者的订阅数据看板',
    track: 'creators', cover: '#FBBF24', coverPattern: 'bars',
    description: 'Substack / Patreon / 小报童一站式看，重点是趋势预测和流失预警。我们用 24 个真实创作者的数据做了模型训练。',
    seeking: ['找投资'],
    tech: ['Python', 'SQL', 'Recharts'],
    team: [{ name: 'Daniel Wu', avatar: 'D', role: '产品' }],
    likes: 22, comments: 5, demo: 'subs.fyi', github: '', submittedAt: '5 月 19 日 17:48',
  },
  {
    id: 'p11', name: 'Echo Notes', tagline: '把会议自动剪辑成可分享的「时间戳片段」',
    track: 'agents', cover: '#60A5FA', coverPattern: 'dots',
    description: '会议结束后自动生成可分享的精彩片段卡片，每个卡片都附上时间戳和上下文摘要。',
    seeking: ['招后端'],
    tech: ['Python', 'Whisper', 'Next.js'],
    team: [{ name: 'Daniel Wu', avatar: 'D', role: '产品' }, { name: 'Maya Patel', avatar: 'M', role: '设计' }],
    likes: 19, comments: 2, demo: '', github: '', submittedAt: '5 月 19 日 17:55',
  },
  {
    id: 'p12', name: 'Slowly', tagline: '强制慢节奏的英语笔友 app',
    track: 'learn', cover: '#FB923C', coverPattern: 'lines',
    description: '信件按距离模拟「慢慢送达」 — 越远的人越慢。鼓励长文和深度交流。',
    seeking: [],
    tech: ['React Native', 'Supabase'],
    team: [{ name: 'Alex Kim', avatar: 'A', role: '前端' }],
    likes: 14, comments: 1, demo: 'slowly.fm', github: '', submittedAt: '5 月 19 日 18:02',
  },
];

// ─── Community members ───
const COMMUNITY_MEMBERS = [
  { id: 'm1', name: '陈思源', handle: 'siyuan', avatar: '陈', avatarColor: '#A3E635', role: '工程师', city: '上海', tagline: '后端 / 隧道工具 / Rust 信徒', skills: ['Go', 'Rust', 'Postgres', 'Redis'], joined: '2024-08-12', projects: 3, contrib: 42, isNew: false, isFollowing: false },
  { id: 'm2', name: 'Maya Patel', handle: 'maya', avatar: 'M', avatarColor: '#F472B6', role: '设计师', city: 'San Francisco', tagline: '产品设计 / 动效 / IDEO 出身', skills: ['Figma', 'Motion', 'Prototyping', 'Research'], joined: '2024-09-01', projects: 5, contrib: 67, isNew: false, isFollowing: true },
  { id: 'm3', name: 'Tomás Reyes', handle: 'tomas', avatar: 'T', avatarColor: '#60A5FA', role: '工程师', city: '智利 · Santiago', tagline: 'WebGL / 协作白板 / 慢节奏开发', skills: ['React', 'TypeScript', 'WebGL', 'Yjs'], joined: '2025-01-18', projects: 2, contrib: 28, isNew: false, isFollowing: false },
  { id: 'm4', name: '王小川', handle: 'xiaochuan', avatar: '王', avatarColor: '#FBBF24', role: '工程师', city: '北京', tagline: 'ByteDance / ML / 隐私技术', skills: ['Python', 'ML', 'K8s', 'Go'], joined: '2025-02-04', projects: 4, contrib: 51, isNew: false, isFollowing: false },
  { id: 'm5', name: 'Jordan Lee', handle: 'jordan', avatar: 'J', avatarColor: '#A78BFA', role: 'PM', city: '深圳', tagline: '独立开发者 / 关注小型工具', skills: ['Figma', 'No-code', 'Analytics', 'SQL'], joined: '2025-03-22', projects: 6, contrib: 38, isNew: false, isFollowing: true },
  { id: 'm6', name: '张语桐', handle: 'yutong', avatar: '张', avatarColor: '#F87171', role: '设计师', city: 'Pittsburgh', tagline: 'CMU HCI / 关注无障碍设计', skills: ['Research', 'Figma', 'SwiftUI', 'A11y'], joined: '2025-04-10', projects: 2, contrib: 19, isNew: false, isFollowing: false },
  { id: 'm7', name: 'Alex Kim', handle: 'alex', avatar: 'A', avatarColor: '#34D399', role: '工程师', city: 'Seoul', tagline: 'KAIST / Vue / 喜欢做小工具', skills: ['Vue', 'Nuxt', 'GraphQL', 'GSAP'], joined: '2025-05-08', projects: 3, contrib: 26, isNew: false, isFollowing: false },
  { id: 'm8', name: '李明轩', handle: 'mingxuan', avatar: '李', avatarColor: '#0EA5E9', role: '工程师', city: '上海', tagline: '上交 / 后端 / 社区运营工具', skills: ['Java', 'Spring', 'Redis', 'K8s'], joined: '2025-06-12', projects: 1, contrib: 14, isNew: false, isFollowing: false },
  { id: 'm9', name: 'Priya Shah', handle: 'priya', avatar: 'P', avatarColor: '#FB923C', role: '工程师', city: 'New York', tagline: 'NYU ITP / 互动装置 / 软硬结合', skills: ['Arduino', 'TouchDesigner', 'p5.js', 'C++'], joined: '2025-08-04', projects: 2, contrib: 17, isNew: false, isFollowing: false },
  { id: 'm10', name: 'Daniel Wu', handle: 'daniel', avatar: 'D', avatarColor: '#A3E635', role: '创始人', city: 'San Francisco', tagline: 'YC W26 / 创作者经济 / 数据', skills: ['Strategy', 'Figma', 'SQL', 'Python'], joined: '2025-09-21', projects: 4, contrib: 45, isNew: false, isFollowing: true },
  { id: 'm11', name: '林知夏', handle: 'zhixia', avatar: '林', avatarColor: '#A3E635', role: '工程师', city: '杭州', tagline: '前端 / 设计系统 / 喜欢小工具', skills: ['React', 'TypeScript', 'Figma', 'Motion'], joined: '2025-09-12', projects: 3, contrib: 31, isNew: false, isFollowing: false, isSelf: true },
  { id: 'm12', name: 'Avery Chen', handle: 'avery', avatar: 'A', avatarColor: '#65A30D', role: '创始人', city: '上海', tagline: 'Hometown 创始人 / 社区运营', skills: ['Strategy', 'Community', 'Writing'], joined: '2024-06-01', projects: 1, contrib: 132, isNew: false, isFollowing: true },
  { id: 'm13', name: 'Sora Tanaka', handle: 'sora', avatar: 'S', avatarColor: '#F472B6', role: '设计师', city: 'Tokyo', tagline: '武藏野美大 / 字体 / 印刷', skills: ['Type Design', 'Print', 'Figma'], joined: '2026-04-02', projects: 0, contrib: 2, isNew: true, isFollowing: false },
  { id: 'm14', name: 'Ravi Mehta', handle: 'ravi', avatar: 'R', avatarColor: '#FBBF24', role: 'PM', city: 'Bangalore', tagline: 'Stripe 早期 PM / 现在做支付基础设施', skills: ['Strategy', 'Payments', 'API Design'], joined: '2026-04-15', projects: 0, contrib: 1, isNew: true, isFollowing: false },
  { id: 'm15', name: 'Naomi Johnson', handle: 'naomi', avatar: 'N', avatarColor: '#60A5FA', role: '工程师', city: 'Berlin', tagline: 'Privacy / E2E / 喜欢密码学', skills: ['Rust', 'Cryptography', 'Linux'], joined: '2026-04-22', projects: 0, contrib: 3, isNew: true, isFollowing: false },
];

// ─── Hackathons (admin) ───
const STARTER_HACKATHONS = [
  {
    id: 'h_2026', name: 'Hometown Hackathon 2026', slug: 'hh-2026',
    status: 'live', // draft | live | reviewing | ended
    theme: 'Tools for Builders',
    tagline: '为 Builder 打造工具的 Builder · 48 小时不间断',
    description: '我们相信最好的工具来自最了解问题的人。Hometown Hackathon 2026 邀请你和你的团队，用 48 小时做一个真正能用的工具 — 自用、给朋友用、给社区用都行。',
    startDate: '2026-05-18', endDate: '2026-05-19',
    submitDeadline: '2026-05-19T18:00',
    location: '上海 · 西岸艺术中心',
    locationType: 'hybrid', // onsite | online | hybrid
    capacity: 200, registered: 47, approved: 32,
    prizePool: 80000, currency: 'CNY',
    tracks: ['Tools for Builders', 'AI Agents', '为创作者', '社区与社交', '健康与生活', '学习工具'],
    sponsors: ['ByteDance', 'Vercel', 'Linear', 'Anthropic'],
    coverColor: '#4D7C0F',
    coverPattern: 'leaves',
    formId: 'f_hack_2026',
    createdBy: 'Avery Chen', createdAt: '2026-04-12', updatedAt: '2026-04-26',
  },
  {
    id: 'h_winter25', name: 'Winter Sprint 2025', slug: 'winter-25',
    status: 'ended',
    theme: 'Less is more',
    tagline: '一周时间，做一个能在 30 秒内讲清楚的小工具',
    description: '冬日里的 7 天 mini-hackathon，鼓励小而美的作品。',
    startDate: '2025-12-09', endDate: '2025-12-15',
    submitDeadline: '2025-12-15T23:59',
    location: '线上',
    locationType: 'online',
    capacity: 100, registered: 86, approved: 86,
    prizePool: 20000, currency: 'CNY',
    tracks: ['工具', '内容', '游戏'],
    sponsors: ['Hometown'],
    coverColor: '#0EA5E9',
    coverPattern: 'waves',
    formId: 'f_winter25', createdBy: 'Avery Chen', createdAt: '2025-11-15', updatedAt: '2025-12-20',
  },
  {
    id: 'h_summer25', name: 'Summer Camp · 设计周', slug: 'design-week',
    status: 'ended',
    theme: '为日常做点什么',
    tagline: '只面向设计师的 5 天创作营',
    description: '把日常的小不爽，重新设计一遍。5 天集中创作 + 一晚展览。',
    startDate: '2025-08-04', endDate: '2025-08-08',
    submitDeadline: '2025-08-08T20:00',
    location: '上海 · 静安',
    locationType: 'onsite',
    capacity: 40, registered: 40, approved: 38,
    prizePool: 12000, currency: 'CNY',
    tracks: ['物理产品', '数字产品', '空间体验'],
    sponsors: ['Hometown', 'Method Studio'],
    coverColor: '#FCE7F3',
    coverPattern: 'circles',
    formId: 'f_design25', createdBy: 'Avery Chen', createdAt: '2025-07-01', updatedAt: '2025-08-12',
  },
  {
    id: 'h_aut26', name: 'Autumn Hack · AI Edition', slug: 'autumn-26',
    status: 'draft',
    theme: '（待定）',
    tagline: '（草稿 — 主题尚未公布）',
    description: '',
    startDate: '2026-09-26', endDate: '2026-09-27',
    submitDeadline: '2026-09-27T20:00',
    location: '（待定）',
    locationType: 'hybrid',
    capacity: 150, registered: 0, approved: 0,
    prizePool: 50000, currency: 'CNY',
    tracks: [],
    sponsors: [],
    coverColor: '#A78BFA',
    coverPattern: 'hex',
    formId: null, createdBy: 'Avery Chen', createdAt: '2026-04-25', updatedAt: '2026-04-25',
  },
];

const STARTER_FIELD_PALETTE = [
  { type: 'short_text', label: '单行文本', icon: 'Type', desc: '姓名、标题等' },
  { type: 'long_text', label: '多行文本', icon: 'AlignLeft', desc: '想法、自我介绍' },
  { type: 'email', label: '邮箱', icon: 'AtSign', desc: '邮箱格式校验' },
  { type: 'phone', label: '手机号', icon: 'Phone', desc: '手机号格式校验' },
  { type: 'url', label: '链接', icon: 'Link', desc: '网址格式校验' },
  { type: 'number', label: '数字', icon: 'Hash', desc: '年龄、人数等' },
  { type: 'radio', label: '单选', icon: 'Radio', desc: '从选项中选一个' },
  { type: 'checkbox', label: '多选', icon: 'CheckSquare', desc: '从选项中选多个' },
  { type: 'select', label: '下拉选择', icon: 'List', desc: '收起的选项列表' },
  { type: 'date', label: '日期', icon: 'Calendar', desc: '日期选择器' },
];

window.HometownData = {
  STARTER_USERS,
  STARTER_FORMS,
  STARTER_HACKATHON_FORM,
  STARTER_APPLICATIONS,
  STARTER_FIELD_PALETTE,
  PROJECT_TRACKS,
  STARTER_PROJECTS,
  COMMUNITY_MEMBERS,
  STARTER_HACKATHONS,
};
